### PR TITLE
noTryCatch option to disable try/catch around spec functions

### PR DESCRIPTION
**Pull request by craigcomstocks**
https://github.com/jasmine/jasmine/issues/1174
https://sencha.jira.com/browse/ORION-1022

### CODE REVIEW

**Comment by craigcomstocks** [comment]
tested with Win7/IE11 and OSX10.11.6/Chrome51 as well as "grunt execSpecsInNode" with node 5.10.1 on OSX.

**Comment by craigcomstocks** [comment]
@dongryphon @joelwatson fixed up PR to go to sencha:no-try-catch as I was intending. Ready for review.

**Comment by joelwatson** [comment]
@dongryphon Any objections to merging this in? Craig has the Sencha Test bits that rely on this ready to go as well. Thanks!

**Comment by dongryphon** [comment]
+1

**Pull request merged**
